import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from '@/components/navbar'
import Cardcontainer from '@/components/cardcontainer'
import Footer from '@/components/footer'
import Hero from '@/components/hero'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Education Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
       <main>
        <Navigation />
        <Hero />
        <Cardcontainer />
        <Footer />
       </main>
    </>
  )
}
